apiVersion: v1
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    creationTimestamp: null
    labels:
      name: locust-master-{{ .Values.loadtest.id }}
      service: seldon
    name: locust-master-{{ .Values.loadtest.id }}
    namespace: {{ .Release.Namespace }}    
  spec:
    replicas: 1
    selector:
      name: locust-master-{{ .Values.loadtest.id }}
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: locust-master-{{ .Values.loadtest.id }}
          service: seldon
      spec:
        containers:
        - command:
          - locust
          - -f
          - /home/seldon/scripts/{{ .Values.locust.script }}
          - --hatch-rate
          - '{{ .Values.locust.hatchRate }}'
          - --clients
          - '{{ .Values.locust.clients }}'
          - --host
          - '{{ .Values.locust.host }}'
          - --master
          - --csv=stats
          - --no-web
          - --expect-slaves
          - '{{ .Values.replicaCount }}'
          env:
          - name: OAUTH_KEY
            value: '{{ .Values.oauth.key }}'
          - name: OAUTH_SECRET
            value: '{{ .Values.oauth.secret }}'
          - name: DATA_SIZE
            value: '{{ .Values.data.size }}'
          - name: OAUTH_ENABLED
            value: '{{ .Values.oauth.enabled }}'
          - name: LOCUSTFILE_PATH
            value: '/home/seldon/scripts/{{ .Values.locust.script }}'
          image: {{ .Values.image.name }}:{{ .Values.image.release }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: payload-config-volume
              readOnly: true
              mountPath: "/home/seldon/resources"
          name: locust-master-{{ .Values.loadtest.id }}
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        volumes:
          - name: payload-config-volume
            configMap:
              name: resources-payload
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 5
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: seldon
    name: locust-master-{{ .Values.loadtest.id }}
  spec:
    ports:
    - name: master-api1
      port: 5557
      protocol: TCP
      targetPort: 5557
    - name: master-api2
      port: 5558
      protocol: TCP
      targetPort: 5558
    - name: master-web
      port: 8089
      protocol: TCP
      targetPort: 8089
    selector:
      name: locust-master-{{ .Values.loadtest.id }}
    sessionAffinity: None
    type: NodePort
kind: List
metadata: {}
